module.exports = {
    serverNames: ["Olvia", "Valencia", "Balenos", "Arsha", "Mediah", "Calpheon", "Velia", "Serendia", "Kamasylvia", "Season", "Rulupee"],
    missions: [
        ["Catch blue-grade fish x13", 150],
        ["Catch blue-grade fish x17", 180],
        ["Catch blue-grade fish x21", 210],
        ["Catch blue-grade fish x8", 120],
        ["Catch green-grade fish x25", 120],
        ["Catch green-grade fish x38", 150],
        ["Catch green-grade fish x50", 180],
        ["Catch green-grade fish x63", 210],
        ["Catch Mackerel x10 and Swordfish x10", 120],
        ["Catch Smokey Chromis x10 and Porgy x10", 120],
        ["Catch Swellfish x10 and Herring x10", 120],
        ["Catch yellow-grade fish x3", 120],
        ["Catch yellow-grade fish x4", 150],
        ["Catch yellow-grade fish x6", 180],
        ["Catch yellow-grade fish x7", 210],
        ["Gather Ash Timber x180", 120],
        ["Gather Ash Timber x360", 120],
        ["Gather Birch Timber x180", 120],
        ["Gather Birch Timber x360", 120],
        ["Gather Cedar Timber x180", 120],
        ["Gather Cedar Timber x360", 120],
        ["Gather Deer Meat x2080", 120],
        ["Gather Deer Meat x2990", 150],
        ["Gather Deer Meat x3510", 180],
        ["Gather Deer Meat x4680", 210],
        ["Gather Dry Mane Grass x1650", 150],
        ["Gather Fairy Powder x125", 120],
        ["Gather Fairy Powder x175", 150],
        ["Gather Fairy Powder x205", 180],
        ["Gather Fairy Powder x280", 210],
        ["Gather Fir Timber x180", 120],
        ["Gather Fir Timber x360", 120],
        ["Gather Fire Flake Flower x1200", 120],
        ["Gather Fire Flake Flower x2500, Dry Mane Grass x1000, and Silk Honey Grass x1000", 210],
        ["Gather Fox Blood x1450", 120],
        ["Gather Fox Blood x2080", 150],
        ["Gather Fox Blood x2470", 180],
        ["Gather Fox Blood x3270", 210],
        ["Gather Iron Ore x150", 120],
        ["Gather Iron Ore x300", 150],
        ["Gather Lamb Meat x2400", 120],
        ["Gather Lamb Meat x3450", 150],
        ["Gather Lamb Meat x4050", 180],
        ["Gather Lamb Meat x5400", 210],
        ["Gather Log x400", 120],
        ["Gather Log x800", 120],
        ["Gather Log x1300", 180],
        ["Gather Log x1800", 210],
        ["Gather Maple Timber x180", 120],
        ["Gather Maple Timber x360", 120],
        ["Gather Pine Timber x180", 120],
        ["Gather Pine Timber x360", 120],
        ["Gather Rough Stone x350", 120],
        ["Gather Rough Stone x700", 120],
        ["Gather Rough Stone x1000", 150],
        ["Gather Rough Stone x1200", 180],
        ["Gather Rough Stone x1600", 210],
        ["Gather Silk Honey Grass x2000 and Fire Flake Flower x1000", 180],
        ["Gather Wild Grass x1600", 120],
        ["Gather Wild Grass x3200", 150],
        ["Gather Wild Grass x3600, Gather Silver Azalea x240, Gather Sunrise Herb x240", 180],
        ["Gather Wild Grass x5600, Silver Azalea x420, Gather Sunrise Herb x420", 210],
        ["Gather Wolf Blood x1450", 120],
        ["Gather Wolf Blood x2080", 150],
        ["Gather Wolf Blood x2470", 180],
        ["Gather Wolf Blood x3270", 210],
        ["Get Milk x1000", 120],
        ["Get Milk x2000", 150],
        ["Get Milk x3000", 180],
        ["Get Milk x4500", 210],
        ["Obtain Bottle of River Water x440", 120],
        ["Obtain Bottle of River Water x580", 150],
        ["Obtain Bottle of River Water x700", 180],
        ["Obtain Bottle of River Water x1000", 210],
        ["Obtain Mysterious Catalyst x10", 120],
        ["Obtain Mysterious Catalyst x15", 150],
        ["Obtain Mysterious Catalyst x20", 180],
        ["Obtain Mysterious Catalyst x24", 210],
        ["Obtain Witch's Delicacy x48", 120],
        ["Obtain Witch's Delicacy x72", 150],
        ["Obtain Witch's Delicacy x96", 180],
        ["Obtain Witch's Delicacy x120", 210],
        ["Gather Fir Timber x180, gather Birch Timber x180", 120],
        ["Gather Fir Timber x90, gather Birch Timber x90", 120],
        ["Gather Log x1200, process Sturdy Pine Plywood x50, process Sturdy Fir Plywood x50", 180],
        ["Gather Log x1600, process Usable Scantling x200", 210],
        ["Gather Log x900, process Pine Plywood x30, process Fir Plywood x30", 150],
        ["Gather Log x900, process Usable Scantling x90", 150],
        ["Gather Maple Timber x180, gather Birch Timber x180", 120],
        ["Gather Maple Timber x90, gather Birch Timber x90", 120],
        ["Gather Rough Stone x1000, process Polished Stone x100", 180],
        ["Gather Rough Stone x1400, Process Polished Stone x200", 210],
        ["Gather Rough Stone x800, process Polished Stone x80", 150],
        ["Defeat Ocean Stalker x2, Defeat Candidum x2", 360],
        ["Defeat Hekaru x2, Defeat Nineshark x1", 300],
        ["Defeat Candidum x2, Defeat Nineshark x2, Defeat Black Rust x1", 420],
        ["Defeat Hekaru x1, Defeat Ocean Stalker x1", 240],
        ["Defeat monsters at Sycraia Underwater Ruins Abyssal Zone x970", 240],
        ["Defeat monsters at Sycraia Underwater Ruins Abyssal Zone x1450", 300],
        ["Defeat monsters at Sycraia Underwater Ruins Abyssal Zone x1930", 360],
        ["Defeat monsters at Sycraia Underwater Ruins Abyssal Zone x2410", 420],
        ["Defeat monsters in Padix Island x770", 240],
        ["Defeat monsters in Padix Island x1160", 300],
        ["Defeat monsters in Padix Island x1550", 360],
        ["Defeat monsters in Padix Island x1930", 420],
        ["Defeat monsters in Sycraia Upper Zone x1500", 240],
        ["Defeat monsters in Sycraia Upper Zone x2240", 300],
        ["Defeat monsters in Sycraia Upper Zone x2990", 360],
        ["Defeat monsters in Sycraia Upper Zone x3740", 420],
        ["Defeat the Protties x1600", 240],
        ["Defeat the Protties x2400", 300],
        ["Defeat the Protties x3200", 360],
        ["Defeat the Protties x4000", 420],
        ["Defeat depraved harbingers at Star's End x760", 120],
        ["Defeat depraved harbingers at Star's End x1130", 180],
        ["Defeat depraved harbingers at Star's End x1510", 210],
        ["Defeat depraved harbingers at Star's End x1900", 240],
        ["Defeat monsters at the Abandoned Monastery x830", 240],
        ["Defeat monsters at the Abandoned Monastery x1250", 300],
        ["Defeat monsters at the Abandoned Monastery x1670", 360],
        ["Defeat monsters at the Abandoned Monastery x2090", 420],
        ["Defeat the Ghosts of Ash Forest x640", 240],
        ["Defeat the Ghosts of Ash Forest x960", 300],
        ["Defeat the Ghosts of Ash Forest x1280", 360],
        ["Defeat the Ghosts of Ash Forest x1600", 420],
        ["Defeat the Specters awakened at Traitor's Graveyard x1500", 240],
        ["Defeat the Specters awakened at Traitor's Graveyard x2250", 300],
        ["Defeat the Specters awakened at Traitor's Graveyard x3000", 360],
        ["Defeat the Specters awakened at Traitor's Graveyard x3750", 420],
        ["Defeat Kagtums at the Blood Wolf Settlement x1670", 120],
        ["Defeat Kagtums at the Blood Wolf Settlement x2500", 180],
        ["Defeat Kagtums at the Blood Wolf Settlement x3340", 210],
        ["Defeat Kagtums at the Blood Wolf Settlement x4170", 240],
        ["Defeat Sherekhans during the day x1340", 150],
        ["Defeat Sherekhans during the day x2000", 190],
        ["Defeat Sherekhans during the day x2670", 220],
        ["Defeat Sherekhans during the day x3340", 260],
        ["Defeat swamp monsters at Tshira Ruins x1500", 90],
        ["Defeat swamp monsters at Tshira Ruins x2250", 150],
        ["Defeat swamp monsters at Tshira Ruins x3000", 180],
        ["Defeat swamp monsters at Tshira Ruins x3750", 210],
        ["Defeat monsters in Mirumok Ruins x833", 120],
        ["Defeat monsters in Mirumok Ruins x1250", 180],
        ["Defeat monsters in Mirumok Ruins x1660", 210],
        ["Defeat monsters in Mirumok Ruins x2090", 240],
        ["Defeat Manshaums at Manshaum Forest x860", 120],
        ["Defeat Manshaums at Manshaum Forest x1300", 180],
        ["Defeat Manshaums at Manshaum Forest x1740", 210],
        ["Defeat Manshaums at Manshaum Forest x2200", 240],
        ["Defeat monsters in Gyfin Rhasia Temple (Party) x433", 120],
        ["Defeat monsters in Gyfin Rhasia Temple (Party) x650", 150],
        ["Defeat monsters in Gyfin Rhasia Temple (Party) x870", 180],
        ["Defeat monsters in Gyfin Rhasia Temple (Party) x1080", 210],
        ["Defeat monsters in Gyfin Rhasia Temple Underground x640", 240],
        ["Defeat monsters in Gyfin Rhasia Temple Underground x960", 300],
        ["Defeat monsters in Gyfin Rhasia Temple Underground x1280", 360],
        ["Defeat monsters in Gyfin Rhasia Temple Underground x1600", 420],
        ["Defeat the Fadus at Loopy Tree Forest x1340", 120],
        ["Defeat the Fadus at Loopy Tree Forest x2000", 150],
        ["Defeat the Fadus at Loopy Tree Forest x2670", 180],
        ["Defeat the Fadus at Loopy Tree Forest x3340", 210],
        ["Defeat the mushrooms in Polly's Forest x1330", 120],
        ["Defeat the mushrooms in Polly's Forest x2000", 150],
        ["Defeat the mushrooms in Polly's Forest x2670", 180],
        ["Defeat the mushrooms in Polly's Forest x3340", 210],
        ["Defeat the Ronaros at Tooth Fairy Forest x1070", 120],
        ["Defeat the Ronaros at Tooth Fairy Forest x1600", 180],
        ["Defeat the Ronaros at Tooth Fairy Forest x2140", 210],
        ["Defeat the Ronaros at Tooth Fairy Forest x2670", 240],
        ["Defeat wild animals at Navarn Steppe x1000", 120],
        ["Defeat wild animals at Navarn Steppe x1500", 180],
        ["Defeat wild animals at Navarn Steppe x2000", 210],
        ["Defeat wild animals at Navarn Steppe x2500", 240],
        ["Defeat Hungry Margoria Sea Monster x10", 240],
        ["Defeat Hungry Margoria Sea Monster x15", 300],
        ["Defeat Hungry Margoria Sea Monster x20", 360],
        ["Defeat Hungry Margoria Sea Monster x25", 420],
        ["Defeat Margoria sea monster x2", 240],
        ["Defeat Margoria sea monster x3", 300],
        ["Defeat Margoria sea monster x4", 360],
        ["Defeat Margoria sea monster x5", 420],
        ["Defeat monsters in Kratuga, Mediah x830", 240],
        ["Defeat monsters in Kratuga, Mediah x1250", 300],
        ["Defeat monsters in Kratuga, Mediah x1660", 360],
        ["Defeat monsters in Kratuga, Mediah x2080", 420],
        ["Defeat Shultz Guards in Mediah x830", 240],
        ["Defeat Shultz Guards in Mediah x1250", 300],
        ["Defeat Shultz Guards in Mediah x1670", 360],
        ["Defeat Shultz Guards in Mediah x2090", 420],        
        ["Defeat monsters in Crypt of Resting Thoughts x300", 240],
        ["Defeat monsters in Crypt of Resting Thoughts x450", 300],
        ["Defeat monsters in Crypt of Resting Thoughts x600", 360],
        ["Defeat monsters in Crypt of Resting Thoughts x750", 420],
        ["Defeat monsters in Olun's Valley x330", 240],
        ["Defeat monsters in Olun's Valley x500", 300],
        ["Defeat monsters in Olun's Valley x670", 360],
        ["Defeat monsters in Olun's Valley x840", 420],
        ["Defeat monsters in Tunkuta x330", 120],
        ["Defeat monsters in Tunkuta x500", 180],
        ["Defeat monsters in Tunkuta x670", 210],
        ["Defeat monsters in Tunkuta x840", 240],
        ["Defeat the Ahibs at Thornwood Forest x850", 120],
        ["Defeat the Ahibs at Thornwood Forest x1270", 180],
        ["Defeat the Ahibs at Thornwood Forest x1700", 210],
        ["Defeat the Ahibs at Thornwood Forest x2120", 240],
        ["Defeat monsters from the Winter Tree Fossil x600", 120],
        ["Defeat monsters from the Winter Tree Fossil x900", 180],
        ["Defeat monsters from the Winter Tree Fossil x1200", 210],
        ["Defeat monsters from the Winter Tree Fossil x1500", 240],
        ["Defeat Okjinsini of Jade Starlight Forest x283", 120],
        ["Defeat Okjinsini of Jade Starlight Forest x425", 180],
        ["Defeat Okjinsini of Jade Starlight Forest x570", 210],
        ["Defeat Okjinsini of Jade Starlight Forest x710", 240],
        ["Defeat the Murraskas in Murrowak's Labyrinth x1000", 120],
        ["Defeat the Murraskas in Murrowak's Labyrinth x1500", 180],
        ["Defeat the Murraskas in Murrowak's Labyrinth x2000", 210],
        ["Defeat the Murraskas in Murrowak's Labyrinth x2500", 240],
        ["Defeat Ancient Civilization Followers in Aakman Temple x1160", 120],
        ["Defeat Ancient Civilization Followers in Aakman Temple x1750", 180],
        ["Defeat Ancient Civilization Followers in Aakman Temple x2330", 210],
        ["Defeat Ancient Civilization Followers in Aakman Temple x2910", 240],
        ["Defeat Ancient Weapons in Hystria Ruins x830", 120],
        ["Defeat Ancient Weapons in Hystria Ruins x1250", 180],
        ["Defeat Ancient Weapons in Hystria Ruins x1670", 210],
        ["Defeat Ancient Weapons in Hystria Ruins x2100", 240],
        ["Defeat Bashims in Valencia x1500", 240],
        ["Defeat Bashims in Valencia x2250", 300],
        ["Defeat Bashims in Valencia x3000", 360],
        ["Defeat Bashims in Valencia x3750", 420],
        ["Defeat Cadry Cultists in Valencia x1330", 240],
        ["Defeat Cadry Cultists in Valencia x2000", 300],
        ["Defeat Cadry Cultists in Valencia x2670", 360],
        ["Defeat Cadry Cultists in Valencia x3330", 420],
        ["Defeat Crescent Cultists in Valencia x1500", 240],
        ["Defeat Crescent Cultists in Valencia x2250", 300],
        ["Defeat Crescent Cultists in Valencia x3000", 360],
        ["Defeat Crescent Cultists in Valencia x3750", 420],
        ["Defeat Desert Fogans in Valencia x1500", 240],
        ["Defeat Desert Fogans in Valencia x2250", 300],
        ["Defeat Desert Fogans in Valencia x3000", 360],
        ["Defeat Desert Fogans in Valencia x3750", 420],
        ["Defeat Desert Nagas in Valencia x1500", 240],
        ["Defeat Desert Nagas in Valencia x2250", 300],
        ["Defeat Desert Nagas in Valencia x3000", 360],
        ["Defeat Desert Nagas in Valencia x3750", 420],
        ["Defeat Waragons in Valencia x830", 240],
        ["Defeat Waragons in Valencia x1250", 300],
        ["Defeat Waragons in Valencia x1660", 360],
        ["Defeat Waragons in Valencia x2080", 420],
        ["Defeat monsters in Pila Ku Jail x1170", 240],
        ["Defeat monsters in Pila Ku Jail x1750", 300],
        ["Defeat monsters in Pila Ku Jail x2340", 360],
        ["Defeat monsters in Pila Ku Jail x2920", 420],
        ["Defeat the Basilisks in Valencia x900", 240],
        ["Defeat the Basilisks in Valencia x1350", 300],
        ["Defeat the Basilisks in Valencia x1800", 360],
        ["Defeat the Basilisks in Valencia x2250", 420],
        ["Defeat the Centaurus in Valencia x930", 240],
        ["Defeat the Centaurus in Valencia x1400", 300],
        ["Defeat the Centaurus in Valencia x1860", 360],
        ["Defeat the Centaurus in Valencia x2340", 420],
        ["Defeat the Gahaz Bandits in Valencia x1500", 240],
        ["Defeat the Gahaz Bandits in Valencia x2250", 300],
        ["Defeat the Gahaz Bandits in Valencia x3000", 360],
        ["Defeat the Gahaz Bandits in Valencia x3750", 420],
        ["Defeat Lava Tribe monsters at the Roud Sulfur Mine x1340", 240],
        ["Defeat Lava Tribe monsters at the Roud Sulfur Mine x2000", 300],
        ["Defeat Lava Tribe monsters at the Roud Sulfur Mine x2670", 360],
        ["Defeat Lava Tribe monsters at the Roud Sulfur Mine x3340", 420],
        ["Barter 25 times", 60],
        ["Barter 50 times", 120],
        ["Barter 75 times", 180],
        ["Barter 150 times", 240],
        ["Deliver Bartali's Odd Adventure to Balker Batian in Calpheon City; Deliver Fresh Fogan Egg to Melissa Brady in Heidel; Deliver Heidel Knights Martial Arts Manual to Lilvanos in Keplan", 90],
        ["Deliver Freharau's Dry Mud to Gabril in Calpheon City; Deliver Heidel First Aid Kit to Hessenvale in the Western Guard Camp", 90],
        ["Deliver Heidel First Aid Kit to Feinia in the Western Guard Camp; Deliver Imp's Red Ore to Kardash in Glish; Deliver Shaia Traditional Hat to Herar in Florin", 90],
        ["Deliver Home Medicine Brewer to Lara in Heidel; Deliver Tree Spirit Seed to Lebyos in Heidel; Deliver Iliya Salt Pot to David Finto in Velia", 90],
        ["Deliver Iliya Salt Pot to Olivia in Heidel; Deliver Heidel Knights Martial Arts Manual to Psebor in Calpheon City", 90],
        ["Deliver Olvia Grape Jam to Amerigo in Heidel; Deliver Ogre Excrement to Lilvanos in Keplan; Deliver Velian Wine to Fredelles Herba in Calpheon City", 90],
        ["Deliver Wishing Kite to Rubin in Calpheon City; Deliver Freharau's Dry Mud to Kaia Feresio in Calpheon City; Deliver Shaia Traditional Hat to Izella in Florin", 90],
        ["Deliver Home Medicine Brewer to Izella in Florin; Deliver Love Potion No. 6 to Geoffrey Erne in Calpheon City; Deliver Imp's Red Ore to Kardash in Glish", 90],
        ["Deliver Emergency Medicine Set to Alchem in Calpheon City; Deliver Imp's Red Ore to Irellio Lucci in Keplan; Deliver Iliya Salt Pot to Olivia in Heidel", 90],
        ["Deliver Fox Fur to Spotty Troll in Trent; Deliver Bartali's Odd Adventure to Phyria in Port Epheria; Deliver Ogre Excrement to Lilvanos in Keplan", 90],
        ["Deliver Bartali's Odd Adventure to Amaranto in Glish; Deliver Lebyos' Leather Shoes to Laniero Lucci in Keplan; Deliver Glish Mud Brick to Angela in Calpheon City", 90],
        ["Deliver Fogan Crescent Spear to Ronatz in Calpheon City; Deliver Iliya Salt Pot to Fredelles Herba in Calpheon City; Deliver Velian Crystal Glass to Irellio Lucci in Keplan", 90],
        ["Deliver Velian Crystal Glass to Seilane in Glish; Deliver Shaia Traditional Hat to Stella in Florin; Deliver Lebyos' Leather Shoes to Christine Cessory in Keplan", 90],
        ["Deliver Magic Binding Oak Branch to Stella in Florin; Deliver Bush Spider Poison Sack to Laniero Lucci in Keplan; Deliver Iliya Salt Pot to Augusta in Trent; Deliver Teviral Scented Candle to Clorince in Velia", 180],
        ["Deliver Valkyrie Painkiller to Isobelle Encarotia in Heidel; Deliver Valentine Salve to Baori in Iliya Island; Deliver Pearl Necklace to Amaranto in Glish; Deliver Pure Iron Ore to Andria in Keplan", 180],
        ["Deliver Confiscated Naga Weapon to Psebor in Calpheon City; Deliver Lebyos' Leather Shoes to Spotty Troll in Trent; Deliver Packaged Pig Barbecue to Olivia in Heidel; Deliver Fish Sausage to Deborah in Glish", 180],
        ["Deliver Emperor's Portrait to Philaberto Falasi in Port Epheria; Deliver Aurobyl Fabric to Zaaira in Velia; Deliver Pack of Old Books to Enrico Mancini in Heidel; Deliver Iliya Salt Pot to Deborah in Glish", 120],
        ["Deliver Poisoned Arrowhead to Lilvanos in Keplan; Deliver Pallet Moving Set to Baori in Iliya Island; Deliver Pack of Old Books to Enrico Mancini in Heidel; Deliver Nymph Costume Set to Kanna in Glish", 180],
        ["Deliver Spider Web Vest to Shurd in Keplan; Deliver Olvia Mountain Cheese to Fredelles Herba in Calpheon City; Deliver Velian Plank to Mayeri in Trent; Deliver Lucky Fish Statue to Ario in Calpheon City", 180],
        ["Deliver Alchemist's Red Reagent to Geranoa in Calpheon City; Deliver Fox Fur to Spotty Troll in Trent; Deliver Pure Iron Ore to Shurd in Keplan;Deliver Dried Fogan Hind Leg to Baori on Iliya Island", 120],
        ["Deliver Chimera's Black Fragment to Srulk at Port Epheria; Deliver Teviral Scented Candle to Eileen in Velia; Deliver Spirit of Earth Sculpture to Ornella in Heidel; Deliver Velian Crystal Glass to Bianstimi in Calpheon City", 120],
        ["Deliver Teviral Scented Candle to Ornella in Heidel; Deliver Calpheon Slum Aid to Ottavio Ferre in Velia; Deliver Fogan Skin Oil to Bevel in Trent; Deliver Madame Pillaf's Ribbon Set to Lavientia Batian in Calpheon City", 120],
        ["Deliver Fogan Skin Oil to Mayeri in Trent; Deliver Fresh Fogan Egg to Phyria in Port Epheria; Deliver Wishing Kite to Lillia on Iliya Island; Deliver Fogan Crescent Spear to Ronatz in Calpheon City", 120],
        ["Deliver Dragon Statue of Oyun to Srulk in Port Epheria; Deliver Fresh Fogan Egg to Lilvanos in Keplan; Deliver Cutting-Edge Dwarf Tool Pack to Mayeri in Trent; Deliver Black Marsh Peat to Grandus in Calpheon City", 180],
        ["Deliver Lucky Fish Statue to Ahr in Calpheon City; Deliver Dragon Statue of Oyun to Lilvayne in Calpheon City; Deliver Freharau's Dry Mud to Baori on Iliya Island; Deliver Fogan Crescent Spear to Andria in Keplan", 120],
        ["Get [Guild] Elastic Palm Plywood, [Guild] Insulating Vanadium Ingot, and [Guild] Sweet Fig from Givel Taric in Valencia City; Trade [Guild] Valencian Specialty to Elswin in Altinova", 150],
        ["Get [Guild] Fine Texture Ash Plywood, [Guild] Golden Copper Ingot, and [Guild] Fresh Chicken from Rosa Kloko in Velia; Trade [Guild] Balenosian Specialty to Roig Mills in Heidel", 150],
        ["Get [Guild] Fragrant Acacia Plywood, [Guild] Pure Zinc Ingot, and [Guild] Sharp Cinnamon from Elswin in Altinova; Trade [Guild] Mediahn Specialty to Givel Taric in Valencia City", 150],
        ["Get [Guild] Hard Pine Plywood, [Guild] Pure Lead Ingot, and [Guild] Soft Fleece from Roig Mills in Heidel; Trade [Guild] Serendian Specialty to Demiel Batian in Calpheon City", 150],
        ["Get [Guild] Thin Fir Plywood, [Guild] Barbaric Tin Ingot, and [Guild] Hardened Coal from Demiel Batian in Calpheon City; Trade [Guild] Calpheonian Specialty to Elswin in Altinova.", 150],
        ["Boss - Defeat Barbarians at the Mediah Abandoned Iron Mine x600", 150],
        ["Boss - Defeat cultists at the Crescent Shrine x300", 90],
        ["Boss - Defeat cultists at the Crescent Shrine x555", 110],
        ["Boss - Defeat cultists at the Crescent Shrine x1026", 120],
        ["Boss - Defeat cultists at the Crescent Shrine x1898", 120],
        ["Boss - Defeat Fogans of Titium Valley x450", 90],
        ["Boss - Defeat Fogans of Titium Valley x832", 110],
        ["Boss - Defeat Fogans of Titium Valley x1539", 120],
        ["Boss - Defeat Fogans of Titium Valley x2847", 120],
        ["Boss - Defeat Desert Nagas at the Desert Naga Temple x480", 90],
        ["Boss - Defeat Desert Nagas at the Desert Naga Temple x888", 110],
        ["Boss - Defeat Desert Nagas at the Desert Naga Temple x1642", 120],
        ["Boss - Defeat Desert Nagas at the Desert Naga Temple x3037", 120],
        ["Boss - Defeat Ferrids at the Omar Lava Cave x280", 120],
        ["Boss - Defeat Ancient Weapons at the Hasrah Ancient Ruins x750", 180],
        ["Boss - Defeat Manes at the Manes Hideout x300", 90],
        ["Boss - Defeat Mutant Test Subjects at Marni's 2nd Lab x250", 90],
        ["Boss - Defeat Sausans at the Sausan Garrison x600", 150],
        ["Boss - Defeat Frenzied Skeletons at the Soldiers' Cemetery x750", 180],
        ["Boss - Defeat Wandering Rogues at the Wandering Rogue Den x300", 120]
};
