module.exports = {
    serverNames: ["Olvia", "Valencia", "Balenos", "Arsha", "Mediah", "Calpheon", "Velia", "Serendia", "Kamasylvia"],
    missions:[
    ["Defeat Mediah Abandoned Iron Mine Barbarian x600", 150],
    ["Defeat Crescent Shrine Argos Saunil x1026", 120],
    ["Defeat Crescent Shrine Argos Saunil x1898", 120],
    ["Defeat Crescent Shrine Argos Saunil x300", 90],
    ["Defeat Crescent Shrine Argos Saunil x555", 110],
    ["Defeat Titium Valley Fogan x1539", 120],
    ["Defeat Titium Valley Fogan x2847", 120],
    ["Defeat Titium Valley Fogan x450", 90],
    ["Defeat Titium Valley Fogan x832", 110],
    ["Defeat Desert Naga Temple Desert Naga x1642", 120],
    ["Defeat Desert Naga Temple Desert Naga x3037", 120],
    ["Defeat Desert Naga Temple Desert Naga x480", 90],
    ["Defeat Desert Naga Temple Desert Naga x888", 110],
    ["Defeat Omar Lava Cave Ferrid x280", 120],
    ["Defeat Hasrah Ancient Ruins Ancient Weapon x750", 180],
    ["Defeat Manes Hideout Mane x300", 90],
    ["Defeat Marni's 2nd Lab Mutant test subject x250", 90],
    ["Defeat Sausan Garrison Sausan x600", 150],
    ["Defeat Soldier's Grave Frenzied Skeleton x750", 180],
    ["Defeat Wandering Rogue Den Wandering Rogue x300", 120],
    ["Fish Grunt x2", 120],
    ["Fish Grunt x4", 120],
    ["Fish Grunt x6", 150],
    ["Fish Grunt x8", 180],
    ["Fish Grunt x10", 210],
    ["Fish Herring x60", 180],
    ["Fish Mackerel x35", 120],
    ["Fish Mudskipper x50", 120],
    ["Fish Mudskipper x100", 120],
    ["Fish Smokey Chromis x10", 210],
    ["Fish Swellfish x70", 240],
    ["Fish Swordfish x30", 150],
    ["Fish Herring x150; Fish Porgy x15", 360],
    ["Gather Ash Timber x180", 120],
    ["Gather Ash Timber x360", 120],
    ["Gather Birch Timber x180", 120],
    ["Gather Birch Timber x360", 120],
    ["Gather Cactus Rind x360", 120],
    ["Gather Cedar Timber x180", 120],
    ["Gather Cedar Timber x360", 120],
    ["Gather Fir Timber x180", 120],
    ["Gather Fir Timber x360", 120],
    ["Gather Maple Timber x180", 120],
    ["Gather Maple Timber x360", 120],
    ["Gather Pine Timber x180", 120],
    ["Gather Pine Timber x360", 120],
    ["Gather Fir Timber x180; Gathering Birch Timber x180", 120],
    ["Gather Fir Timber x90; Gather Birch Timber x90", 120],
    ["Gather Maple Timber x180; Gathering Birch Timber x180", 120],
    ["Gather Maple Timber x90; Gather Birch Timber x90", 120],
    ["Gather Palm Timber x180; Gather Elder Tree Timber x180", 120],
    ["Gather Iron Ore x150", 120],
    ["Gather Iron Ore x300", 120],
    ["Gather Log x400", 120],
    ["Gather Log x800", 120],
    ["Gather Log x1300", 180],
    ["Gather Log x1800", 210],
    ["Gather Log x900; Process Pine Plywood x30; Process Fir Plywood x30", 150],
    ["Gather Log x900; Process Usable Scantling x90", 150],
    ["Gather Log x1200; Process Sturdy Pine Plywood x50; Process Sturdy Fir Plywood x50", 180],
    ["Gather Log x1600; Process Usable Scantling x200", 210],
    ["Gather Rough Stone x350", 120],
    ["Gather Rough Stone x700", 120],
    ["Gather Rough Stone x1000", 150],
    ["Gather Rough Stone x1200", 180],
    ["Gather Rough Stone x1600", 210],
    ["Gather Rough Stone x800; Process Polished Stone x80", 150],
    ["Gather Rough Stone x1000; Process Polished Stone x100", 180],
    ["Gather Rough Stone x1400, Process Polished Stone x200", 210],
    ["Gather Rough Opal x5; Process Melted Iron Shard x50", 120],
    ["Gather Rough Opal x8; Process Melted Iron Shard x100", 120],
    ["Gather Coral Piece x40, Gather Seaweed x40, Gather Clam x10, Fish Porgy x5", 120],
    ["Gather Coral Piece x60, Gather Oyster x60, Gather Clam x20, Fish Tuna x10", 150],
    ["Gather Coral Piece x40, Gather Oyster x40, Gather Clam x10, Fish Yellow Swordfish x5", 120],
    ["Gather Coral Piece x60, Gather Seaweed x60, Gather Clam x20, Fish Striped Jewfish x10", 150],
    ["Gather Tangleweed x80, Gather Seaweed x80, Gather Clam x30, Fish Nibbler x15", 210],
    ["Gather Tangleweed x80, Gather Oyster x80, Gather Clam x30, Fish Marlin x15", 210],
    ["Gather Tangleweed x100, Gather Seaweed x100, Gather Clam x40, Fish Striped Bonito x20", 300],
    ["Gather Tangleweed x100, Gather Oyster x100, Gather Clam x40, Fish Sunfish x20", 300],
    ["Defeat Ocean Stalker x2, Defeat Candidum x2", 360],
    ["Defeat Hekaru x2, Defeat Nineshark x1", 300],
    ["Defeat Hekaru x1, Defeat Ocean Stalker x1", 240],
    ["Defeat Candidum x2, Defeat Nineshark x2, Defeat Black Rust x1", 420],
    ["Defeat Calpheon Shrine enemy x700", 90],
    ["Defeat Calpheon Shrine enemy x1500", 120],
    ["Defeat Calpheon Shrine enemy x2500", 150],
    ["Defeat Calpheon Shrine enemy x3700", 180],
    ["Defeat Calpheon Shrine enemy x4500", 210],
    ["Defeat Calpheon Southwestern Treant x800", 90],
    ["Defeat Cyclops x20", 90],
    ["Defeat Cyclops x40", 120],
    ["Defeat Cyclops x65", 150],
    ["Defeat Cyclops x100", 180],
    ["Defeat Cyclops x150", 210],
    ["Defeat Hexe Sanctuary Skeleton x800", 90],
    ["Defeat Hexe Sanctuary Skeleton x1800", 120],
    ["Defeat Hexe Sanctuary Skeleton x2800", 150],
    ["Defeat Hexe Sanctuary Skeleton x4000", 180],
    ["Defeat Hexe Sanctuary Skeleton x5000", 210],
    ["Defeat Keplan Primal Giant Post Giant x1000", 90],
    ["Defeat Keplan Primal Giant Post Giant x2500", 120],
    ["Defeat Keplan Primal Giant Post Giant x4000", 150],
    ["Defeat Keplan Primal Giant Post Giant x5500", 180],
    ["Defeat Keplan Primal Giant Post Giant x7000", 210],
    ["Defeat Southwestern Calpheon Mansha x1000", 90],
    ["Defeat Southwestern Calpheon Mansha x2500", 120],
    ["Defeat Southwestern Calpheon Mansha x4000", 150],
    ["Defeat Southwestern Calpheon Mansha x5500", 180],
    ["Defeat Southwestern Calpheon Mansha x7000", 210],
    ["Defeat Southwestern Calpheon Rhutum x1000", 90],
    ["Defeat Southwestern Calpheon Rhutum x2500", 120],
    ["Defeat Southwestern Calpheon Rhutum x4000", 150],
    ["Defeat Southwestern Calpheon Rhutum x5500", 180],
    ["Defeat Southwestern Calpheon Rhutum x7000", 210],
    ["Defeat Southwestern Calpheon Tree Spirit x2000", 120],
    ["Defeat Southwestern Calpheon Tree Spirit x3200", 150],
    ["Defeat Southwestern Calpheon Tree Spirit x4800", 180],
    ["Defeat Southwestern Calpheon Tree Spirit x6500", 210],
    ["Defeat Blood Wolf Town Kagtum x910", 120],
    ["Defeat Blood Wolf Town Kagtum x1820", 180],
    ["Defeat Blood Wolf Town Kagtum x2660", 210],
    ["Defeat Blood Wolf Town Kagtum x3570", 240],
    ["Defeat Sherekhan x520 during the day", 150],
    ["Defeat Sherekhan x1040 during the day", 190],
    ["Defeat Sherekhan x1520 during the day", 220],
    ["Defeat Sherekhan x2040 during the day", 260],
    ["Defeat Tshira Ruins enemy x1300", 90],
    ["Defeat Tshira Ruins enemy x2600", 150],
    ["Defeat Tshira Ruins enemy x3800", 180],
    ["Defeat Tshira Ruins enemy x5100", 210],
    ["Defeat Loopy Tree Forest Fadus x1000", 90],
    ["Defeat Loopy Tree Forest Fadus x2000", 150],
    ["Defeat Loopy Tree Forest Fadus x3500", 180],
    ["Defeat Loopy Tree Forest Fadus x5000", 210],
    ["Defeat Manshaum Forest Manshaum x1000", 120],
    ["Defeat Manshaum Forest Manshaum x2000", 180],
    ["Defeat Manshaum Forest Manshaum x3000", 210],
    ["Defeat Manshaum Forest Manshaum x4000", 240],
    ["Defeat Navarn Steppe Animal x1000", 120],
    ["Defeat Navarn Steppe Animal x1500", 180],
    ["Defeat Navarn Steppe Animal x2200", 210],
    ["Defeat Navarn Steppe Animal x3000", 240],
    ["Defeat Polly's Forest Mushroom x1000", 90],
    ["Defeat Polly's Forest Mushroom x2000", 150],
    ["Defeat Polly's Forest Mushroom x3500", 180],
    ["Defeat Polly's Forest Mushroom x5000", 210],
    ["Defeat Hungry Margoria Sea Monster x10", 240],
    ["Defeat Hungry Margoria Sea Monster x15", 300],
    ["Defeat Hungry Margoria Sea Monster x20", 360],
    ["Defeat Hungry Margoria Sea Monster x25", 420],
    ["Defeat Manes Hideout Mane x2200", 120],
    ["Defeat Manes Hideout Mane x3000", 150],
    ["Defeat Manes Hideout Mane x4800", 180],
    ["Defeat Manes Hideout Mane x6100", 210],
    ["Defeat Mediah Abandoned Iron Mine Barbarian x1200", 90],
    ["Defeat Mediah Abandoned Iron Mine Barbarian x2000", 120],
    ["Defeat Mediah Abandoned Iron Mine Barbarian x3200", 150],
    ["Defeat Mediah Abandoned Iron Mine Barbarian x4800", 180],
    ["Defeat Mediah Abandoned Iron Mine Barbarian x6800", 210],
    ["Defeat Mediah Elric Shrine enemy x1000", 90],
    ["Defeat Mediah Elric Shrine enemy x2200", 120],
    ["Defeat Mediah Elric Shrine enemy x2900", 150],
    ["Defeat Mediah Elric Shrine enemy x4200", 180],
    ["Defeat Mediah Elric Shrine enemy x5200", 210],
    ["Defeat Mediah Helm x1200", 90],
    ["Defeat Mediah Helm x2000", 120],
    ["Defeat Mediah Helm x3200", 150],
    ["Defeat Mediah Helm x4200", 180],
    ["Defeat Mediah Helm x6300", 210],
    ["Defeat Sausan Garrison Sausan x800", 90],
    ["Defeat Sausan Garrison Sausan x1800", 120],
    ["Defeat Sausan Garrison Sausan x2300", 150],
    ["Defeat Sausan Garrison Sausan x3300", 180],
    ["Defeat Sausan Garrison Sausan x5600", 210],
    ["Defeat Wandering Rogue Den Wandering Rogue x1200", 90],
    ["Defeat Wandering Rogue Den Wandering Rogue x2200", 120],
    ["Defeat Wandering Rogue Den Wandering Rogue x3000", 150],
    ["Defeat Wandering Rogue Den Wandering Rogue x4800", 180],
    ["Defeat Wandering Rogue Den Wandering Rogue x6100", 210],
    ["Defeat Waragons in Valencia x1800", 240],
    ["Defeat Waragons in Valencia x2500", 300],
    ["Defeat Waragons in Valencia x3500", 360],
    ["Defeat Waragons in Valencia x4500", 420],
    ["Defeat Crescent Shrine Argos Saunil x1800", 240],
    ["Defeat Crescent Shrine Argos Saunil x2500", 300],
    ["Defeat Crescent Shrine Argos Saunil x3500", 360],
    ["Defeat Crescent Shrine Argos Saunil x4500", 420],
    ["Defeat Desert Naga Temple Desert Naga x1800", 240],
    ["Defeat Desert Naga Temple Desert Naga x2500", 300],
    ["Defeat Desert Naga Temple Desert Naga x3500", 360],
    ["Defeat Desert Naga Temple Desert Naga x4500", 420],
    ["Defeat Titium Valley Fogan x1800", 240],
    ["Defeat Titium Valley Fogan x2500", 300],
    ["Defeat Titium Valley Fogan x3500", 360],
    ["Defeat Titium Valley Fogan x4500", 420],
    ["Defeat Valencia Bashim x1800", 240],
    ["Defeat Valencia Bashim x2500", 300],
    ["Defeat Valencia Bashim x3500", 360],
    ["Defeat Valencia Bashim x4500", 420],
    ["Defeat Valencia Basilisk x1500", 240],
    ["Defeat Valencia Basilisk x2000", 300],
    ["Defeat Valencia Basilisk x2800", 360],
    ["Defeat Valencia Basilisk x3800", 420],
    ["Defeat Valencia Cadry enemy x1800", 240],
    ["Defeat Valencia Cadry enemy x2500", 300],
    ["Defeat Valencia Cadry enemy x3500", 360],
    ["Defeat Valencia Cadry enemy x4500", 420],
    ["Defeat Valencia Centaurus x1500", 240],
    ["Defeat Valencia Centaurus x2000", 300],
    ["Defeat Valencia Centaurus x2800", 360],
    ["Defeat Valencia Centaurus x3800", 420],
    ["Defeat Valencia Gahaz Bandit x1800", 240],
    ["Defeat Valencia Gahaz Bandit x2500", 300],
    ["Defeat Valencia Gahaz Bandit x3500", 360],
    ["Defeat Valencia Gahaz Bandit x4500", 420],
    ["Defeat Margoria sea monster x2", 240],
    ["Defeat Margoria sea monster x3", 300],
    ["Defeat Margoria sea monster x4", 360],
    ["Defeat Margoria sea monster x5", 420],
    ["Deliver Bartali's Odd Adventure to Balker Batian in Calpheon City; Deliver Fresh Fogan Egg to Melissa Brady in Heidel; Deliver Heidel Knights Martial Arts Manual to Lilvanos in Keplan", 90],
    ["Deliver Freharau's Dry Mud to Gabril in Calpheon City; Deliver Heidel First Aid Kit to Hessenvale in the Western Guard Camp", 90],
    ["Deliver Heidel First Aid Kit to Feinia in the Western Guard Camp; Deliver Imp's Red Ore to Kardash in Glish; Deliver Shaia Traditional Hat to Herar in Florin", 90],
    ["Deliver Home Medicine Brewer to Lara in Heidel; Deliver Tree Spirit Seed to Lebyos in Heidel; Deliver Iliya Salt Pot to David Finto in Velia", 90],
    ["Deliver Iliya Salt Pot to Olivia in Heidel; Deliver Heidel Knights Martial Arts Manual to Psebor in Calpheon City", 90],
    ["Deliver Olvia Grape Jam to Amerigo in Heidel; Deliver Ogre Excrement to Lilvanos in Keplan; Deliver Velian Wine to Fredelles Herba in Calpheon City", 90],
    ["Deliver Wishing Kite to Rubin in Calpheon City; Deliver Freharau's Dry Mud to Kaia Feresio in Calpheon City; Deliver Shaia Traditional Hat to Izella in Florin", 90],
    ["Deliver Home Medicine Brewer to Izella in Florin; Deliver Love Potion No. 6 to Geoffrey Erne in Calpheon City; Deliver Imp's Red Ore to Kardash in Glish", 90],
    ["Deliver Emergency Medicine Set to Alchem in Calpheon City; Deliver Imp's Red Ore to Irellio Lucci in Keplan; Deliver Iliya Salt Pot to Olivia in Heidel", 90],
    ["Deliver Fox Fur to Spotty Troll in Trent; Deliver Bartali's Odd Adventure to Phyria in Port Epheria; Deliver Ogre Excrement to Lilvanos in Keplan", 90],
    ["Deliver Bartali's Odd Adventure to Amaranto in Glish; Deliver Lebyos' Leather Shoes to Laniero Lucci in Keplan; Deliver Glish Mud Brick to Angela in Calpheon City", 90],
    ["Deliver Fogan Crescent Spear to Ronatz in Calpheon City; Deliver Iliya Salt Pot to Fredelles Herba in Calpheon City; Deliver Velian Crystal Glass to Irellio Lucci in Keplan", 90],
    ["Deliver Velian Crystal Glass to Seilane in Glish; Deliver Shaia Traditional Hat to Stella in Florin; Deliver Lebyos' Leather Shoes to Christine Cessory in Keplan", 90],
    ["Deliver Magic Binding Oak Branch to Stella in Florin; Deliver Bush Spider Poison Sack to Laniero Lucci in Keplan; Deliver Iliya Salt Pot to Augusta in Trent; Deliver Teviral Scented Candle to Clorince in Velia", 180],
    ["Deliver Valkyrie Painkiller to Isobelle Encarotia in Heidel; Deliver Valentine Salve to Baori in Iliya Island; Deliver Pearl Necklace to Amaranto in Glish; Deliver Pure Iron Ore to Andria in Keplan", 180],
    ["Deliver Confiscated Naga Weapon to Psebor in Calpheon City; Deliver Lebyos' Leather Shoes to Spotty Troll in Trent; Deliver Packaged Pig Barbecue to Olivia in Heidel; Deliver Fish Sausage to Deborah in Glish", 180],
    ["Deliver Emperor's Portrait to Philaberto Falasi in Port Epheria; Deliver Aurobyl Fabric to Zaaira in Velia; Deliver Pack of Old Books to Enrico Mancini in Heidel; Deliver Iliya Salt Pot to Deborah in Glish", 120],
    ["Deliver Poisoned Arrowhead to Lilvanos in Keplan; Deliver Pallet Moving Set to Baori in Iliya Island; Deliver Pack of Old Books to Enrico Mancini in Heidel; Deliver Nymph Costume Set to Kanna in Glish", 180],
    ["Deliver Spider Web Vest to Shurd in Keplan; Deliver Olvia Mountain Cheese to Fredelles Herba in Calpheon City; Deliver Velian Plank to Mayeri in Trent; Deliver Lucky Fish Statue to Ario in Calpheon City", 180],
    ["Deliver Alchemist's Red Reagent to Geranoa in Calpheon City; Deliver Fox Fur to Spotty Troll in Trent; Deliver Pure Iron Ore to Shurd in Keplan;Deliver Dried Fogan Hind Leg to Baori on Iliya Island", 120],
    ["Deliver Chimera's Black Fragment to Srulk at Port Epheria; Deliver Teviral Scented Candle to Eileen in Velia; Deliver Spirit of Earth Sculpture to Ornella in Heidel; Deliver Velian Crystal Glass to Bianstimi in Calpheon City", 120],
    ["Deliver Teviral Scented Candle to Ornella in Heidel; Deliver Calpheon Slum Aid to Ottavio Ferre in Velia; Deliver Fogan Skin Oil to Bevel in Trent; Deliver Madame Pillaf's Ribbon Set to Lavientia Batian in Calpheon City", 120],
    ["Deliver Fogan Skin Oil to Mayeri in Trent; Deliver Fresh Fogan Egg to Phyria in Port Epheria; Deliver Wishing Kite to Lillia on Iliya Island; Deliver Fogan Crescent Spear to Ronatz in Calpheon City", 120],
    ["Deliver Dragon Statue of Oyun to Srulk in Port Epheria; Deliver Fresh Fogan Egg to Lilvanos in Keplan; Deliver Cutting-Edge Dwarf Tool Pack to Mayeri in Trent; Deliver Black Marsh Peat to Grandus in Calpheon City", 180],
    ["Deliver Lucky Fish Statue to Ahr in Calpheon City; Deliver Dragon Statue of Oyun to Lilvayne in Calpheon City; Deliver Freharau's Dry Mud to Baori on Iliya Island; Deliver Fogan Crescent Spear to Andria in Keplan", 120],
    ["Get [Guild] Elastic Palm Plywood, [Guild] Insulating Vanadium Ingot, and [Guild] Sweet Fig from Givel Taric in Valencia City; Trade [Guild] Valencian Specialty to Elswin in Altinova", 150],
    ["Get [Guild] Fine Texture Ash Plywood, [Guild] Golden Copper Ingot, and [Guild] Fresh Chicken from Rosa Kloko in Velia; Trade [Guild] Balenosian Specialty to Roig Mills in Heidel", 150],
    ["Get [Guild] Fragrant Acacia Plywood, [Guild] Pure Zinc Ingot, and [Guild] Sharp Cinnamon from Elswin in Altinova; Trade [Guild] Mediahn Specialty to Givel Taric in Valencia City", 150],
    ["Get [Guild] Hard Pine Plywood, [Guild] Pure Lead Ingot, and [Guild] Soft Fleece from Roig Mills in Heidel; Trade [Guild] Serendian Specialty to Demiel Batian in Calpheon City", 150],
    ["Get [Guild] Thin Fir Plywood, [Guild] Barbaric Tin Ingot, and [Guild] Hardened Coal from Demiel Batian in Calpheon City; Trade [Guild] Calpheonian Specialty to Elswin in Altinova.", 150],
    ["Barter 25 times", 60],
    ["Barter 50 times", 120],
    ["Barter 75 times", 180],
    ["Barter 150 times", 240],
    ["Get Milk x1000", 120],
    ["Get Milk x2000", 150],
    ["Get Milk x3000", 180],
    ["Get Milk x4500", 210],
    ["Gather Weeds x800", 120],
    ["Gather Weeds x1600", 150],
    ["Gather Weeds x1800, Silver Azalea x240, Sunrise Herb x240", 180],
    ["Gather Weeds x2800, Gather Silver Azalea x420, Gather Sunrise Herb x420", 210],
    ["Mission Objective: Gather Wild Grass x1600", 120],
    ["Mission Objective: Gather Wild Grass x3200", 150],
    ["Mission Objective: Gather Wild Grass x3600, Gather Silver Azalea x240, Gather Sunrise Herb x240", 180],
    ["Mission Objective: Gather Wild Grass x5600, Silver Azalea x420, Gather Sunrise Herb x420", 210],
    ["Mission Objective: Defeat the Ancient Weapons in Hystria Ruins x700", 120],
    ["Mission Objective: Defeat the Ancient Weapons in Hystria Ruins x1050", 180],
    ["Mission Objective: Defeat the Ancient Weapons in Hystria Ruins x1540", 210],
    ["Mission Objective: Defeat the Ancient Weapons in Hystria Ruins x2100", 240],
    ["Mission Objective: Defeat the Ancient Civilization Followers in Aakman Temple x1000", 120],
    ["Mission Objective: Defeat the Ancient Civilization Followers in Aakman Temple x1500", 180],
    ["Mission Objective: Defeat the Ancient Civilization Followers in Aakman Temple x2200", 210],
    ["Mission Objective: Defeat the Ancient Civilization Followers in Aakman Temple x3000", 240],
    ["Mission Objective: Defeat depraved harbingers at Star's End x1000", 120],
    ["Mission Objective: Defeat depraved harbingers at Star's End x1500", 180],
    ["Mission Objective: Defeat depraved harbingers at Star's End x2200", 210],
    ["Mission Objective: Defeat depraved harbingers at Star's End x3000", 240]
]
};